#!/usr/bin/env python3

import os, stat
import subprocess
import sys

scriptpath = os.path.dirname(os.path.realpath(__file__))

python_version = sys.version_info[:2]
pver = '.'.join(map(str, python_version))

exe = os.path.join(scriptpath, f"../lib/python{pver}/site-packages/ZarrSeg/main.py")
os.chmod(exe, stat.S_IRWXU|stat.S_IRWXG|stat.S_IRWXO)

# command = 'conda run -n ZarrSeg %s' % exe
command = exe
for item in sys.argv[1:]:
    command = command + ' ' + item

subprocess.run(command, shell = True)
